# Generated by Django 3.2.5 on 2022-06-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmsg',
            old_name='user',
            new_name='userprf',
        ),
    ]
