# Generated by Django 3.2.5 on 2022-09-25 08:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('bbs', '0003_postmsg_imgflg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Re_postmsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=5000)),
                ('img', models.ImageField(blank=True, null=True, upload_to='postimgs/')),
                ('imgflg', models.BooleanField(default=True)),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_msg', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bbs.postmsg')),
                ('userprf', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userprofile.userprofile')),
            ],
        ),
    ]
