# Generated by Django 3.2.5 on 2022-06-25 15:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=5000)),
                ('img', models.ImageField(blank=True, null=True, upload_to='dmimgs/')),
                ('imgflg', models.BooleanField(default=True)),
                ('sdtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('rcvprf', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rcvDm', to='userprofile.userprofile')),
                ('sdprf', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sendDm', to='userprofile.userprofile')),
            ],
        ),
    ]
